version: "3.5"

services:
  product:
    build:
      context: ./ms-product
    command: npm start
    ports: 
      - 3000:3000
    volumes:
      - ./ms-product:/usr/app
  db:
    image: mysql
    command: 
        --default-authentication-plugin=mysql_native_password
        --init-file /data/application/init.sql
    ports:
        - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
        - ./db-volume/init.sql:/data/application/init.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080