version: "3.5"

services:
  product:
    build:
      context: ./ms-product
    command: npm start
    ports: 
      - 3000:3000
    volumes:
      - ./ms-product:/usr/ms-product
  order:
    build:
      context: ./ms-order
    command: npm start
    ports: 
      - 3536:3536
    volumes:
      - ./ms-order:/usr/ms-order
  shipping:
    build:
      context: ./ms-shipping
    command: npm start
    ports: 
      - 3535:3535
    volumes:
      - ./ms-shipping:/usr/ms-shipping
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - 3306:3306
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: amazondb
    volumes:
        - ./localdb:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  consul:
    image: consul
    restart: always
    ports:
      - 8500:8500