version: "3.5"

services:
  product:
    image: acoeelho/case-amazon_product
    environment:
      NODE_PORT: 3001
    ports: 
      - 3001:3001
    volumes:
      - ./ms-product:/usr/app
  desk:
    image: acoeelho/case-amazon_desk
    environment:
      NODE_PORT: 3002
    ports: 
      - 3002:3002
    volumes:
      - ./ms-desk:/usr/app
  wishlist:
    image: acoeelho/case-amazon_wishlist
    environment:
      NODE_PORT: 3003
    ports: 
      - 3003:3003
    volumes:
      - ./ms-wishlist:/usr/app
  db:
    image: mysql
    command: 
        --default-authentication-plugin=mysql_native_password
        --init-file /data/application/init.sql
    ports:
        - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
        - ./db-volume/init.sql:/data/application/init.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock