version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "amazon-topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
  product:
    image: acoeelho/case-amazon_product
    depends_on:
      - zookeeper
      - kafka
      - db
    command: sh -c "dockerize -wait tcp://host.docker.internal:2181 -wait tcp://host.docker.internal:9092 npm start"
    environment:
      NODE_PORT: 3001
    ports: 
      - 3001:3001
    volumes:
      - ./ms-product:/usr/ms-product
  db:
    image: mysql
    command: 
        --default-authentication-plugin=mysql_native_password
        --init-file /data/application/init.sql
    ports:
        - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
        - ./db-volume/init.sql:/data/application/init.sql