version: "3.5"

services:
  product:
    build:
      context: ./ms-product
    command: npm start
    ports: 
      - 3000:3000
    volumes:
      - ./ms-product:/usr/app
  db:
    image: mysql
    command: 
        --default-authentication-plugin=mysql_native_password
        --init-file /data/application/init.sql
    ports:
        - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
        - ./db-volume/init.sql:/data/application/init.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock