-- MySQL Script generated by MySQL Workbench
-- Fri Oct  9 20:13:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema amazon
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `amazon` ;

-- -----------------------------------------------------
-- Schema amazon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `amazon` DEFAULT CHARACTER SET utf8 ;
USE `amazon` ;

-- -----------------------------------------------------
-- Table `amazon`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon`.`product` ;

CREATE TABLE IF NOT EXISTS `amazon`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(100) NULL,
  `product_desc` VARCHAR(500) NULL,
  `product_price` DECIMAL NULL,
  `product_keywords` VARCHAR(200) NULL,
  `product_amount` INT NULL,
  `product_category` VARCHAR(100) NULL,
  `product_views` INT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazon`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon`.`user` ;

CREATE TABLE IF NOT EXISTS `amazon`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(100) NULL,
  `user_address` VARCHAR(200) NULL,
  `user_cep` VARCHAR(8) NULL,
  `user_cpf` VARCHAR(11) NULL,
  `user_birth` DATETIME NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazon`.`desk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon`.`desk` ;

CREATE TABLE IF NOT EXISTS `amazon`.`desk` (
  `desk_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_user_id` INT NOT NULL,
  `desk_desc` VARCHAR(200) NULL,
  `desk_date` DATETIME NULL,
  PRIMARY KEY (`desk_id`),
  INDEX `fk_chamado_usuario1_idx` (`usuario_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_chamado_usuario1`
    FOREIGN KEY (`usuario_user_id`)
    REFERENCES `amazon`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazon`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon`.`table1` ;

CREATE TABLE IF NOT EXISTS `amazon`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazon`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon`.`order` ;

CREATE TABLE IF NOT EXISTS `amazon`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `order_payment` VARCHAR(15) NULL,
  `usuario_user_id` INT NOT NULL,
  `order_tax` DECIMAL NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_pedido_usuario1_idx` (`usuario_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`usuario_user_id`)
    REFERENCES `amazon`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazon`.`user_has_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon`.`user_has_product` ;

CREATE TABLE IF NOT EXISTS `amazon`.`user_has_product` (
  `produto_product_id` INT NOT NULL,
  `usuario_user_id` INT NOT NULL,
  PRIMARY KEY (`produto_product_id`, `usuario_user_id`),
  INDEX `fk_produto_has_usuario_usuario1_idx` (`usuario_user_id` ASC) VISIBLE,
  INDEX `fk_produto_has_usuario_produto_idx` (`produto_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_usuario_produto`
    FOREIGN KEY (`produto_product_id`)
    REFERENCES `amazon`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_usuario_usuario1`
    FOREIGN KEY (`usuario_user_id`)
    REFERENCES `amazon`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazon`.`product_has_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `amazon`.`product_has_order` ;

CREATE TABLE IF NOT EXISTS `amazon`.`product_has_order` (
  `produto_product_id` INT NOT NULL,
  `pedido_order_id` INT NOT NULL,
  PRIMARY KEY (`produto_product_id`, `pedido_order_id`),
  INDEX `fk_produto_has_pedido_pedido1_idx` (`pedido_order_id` ASC) VISIBLE,
  INDEX `fk_produto_has_pedido_produto1_idx` (`produto_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_pedido_produto1`
    FOREIGN KEY (`produto_product_id`)
    REFERENCES `amazon`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_pedido_pedido1`
    FOREIGN KEY (`pedido_order_id`)
    REFERENCES `amazon`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
